### ISSUE TITLE
Calling `FreeFont` with current using font results "FreeFont: Font doesn't exist."

### ISSUE THREAD

**Issue by EasyT-T** [ZiYueCommentary/Blitz3D#11]

**Comment by ZiYueCommentary** [comment]
The simplest way to reimplement this:
```basic
FreeFont(CurrentFont())
```

**Comment by ZiYueCommentary** [comment]
This happened in the case of the current font is default font. It does not exist in the font set and resource set, which the engine to determine whether it is a font. When invoking functions which are related to the font, the function will check whether the font exists before executing. Due to the default font did not exist in any list, so the function will assert that the font does not exist, causing the runtime exception.
